enum Currency {
  usd('USD', 'US Dollar', '\$'),
  eur('EUR', 'Euro', '€'),
  gbp('GBP', 'British Pound', '£'),
  jpy('JPY', 'Japanese Yen', '¥'),
  cny('CNY', 'Chinese Yuan', '¥'),
  inr('INR', 'Indian Rupee', '₹'),
  cad('CAD', 'Canadian Dollar', 'C\$'),
  aud('AUD', 'Australian Dollar', 'A\$'),
  nzd('NZD', 'New Zealand Dollar', 'NZ\$'),
  chf('CHF', 'Swiss Franc', 'Fr'),
  sek('SEK', 'Swedish Krona', 'kr'),
  nok('NOK', 'Norwegian Krone', 'kr'),
  dkk('DKK', 'Danish Krone', 'kr'),
  rub('RUB', 'Russian Ruble', '₽'),
  brl('BRL', 'Brazilian Real', 'R\$'),
  mxn('MXN', 'Mexican Peso', '\$'),
  zar('ZAR', 'South African Rand', 'R'),
  sgd('SGD', 'Singapore Dollar', 'S\$'),
  hkd('HKD', 'Hong Kong Dollar', 'HK\$'),
  krw('KRW', 'South Korean Won', '₩'),
  thb('THB', 'Thai Baht', '฿'),
  myr('MYR', 'Malaysian Ringgit', 'RM'),
  idr('IDR', 'Indonesian Rupiah', 'Rp'),
  php('PHP', 'Philippine Peso', '₱'),
  vnd('VND', 'Vietnamese Dong', '₫'),
  egp('EGP', 'Egyptian Pound', 'E£'),
  sar('SAR', 'Saudi Riyal', '﷼'),
  aed('AED', 'UAE Dirham', 'د.إ'),
  try_('TRY', 'Turkish Lira', '₺'),
  pln('PLN', 'Polish Zloty', 'zł'),
  ils('ILS', 'Israeli Shekel', '₪'),
  ars('ARS', 'Argentine Peso', '\$'),
  clp('CLP', 'Chilean Peso', '\$'),
  cop('COP', 'Colombian Peso', '\$'),
  pen('PEN', 'Peruvian Sol', 'S/'),
  czk('CZK', 'Czech Koruna', 'Kč'),
  huf('HUF', 'Hungarian Forint', 'Ft'),
  ron('RON', 'Romanian Leu', 'lei'),
  bgn('BGN', 'Bulgarian Lev', 'лв'),
  hrk('HRK', 'Croatian Kuna', 'kn'),
  isk('ISK', 'Icelandic Króna', 'kr'),
  mad('MAD', 'Moroccan Dirham', 'د.م.'),
  tnd('TND', 'Tunisian Dinar', 'د.ت'),
  jod('JOD', 'Jordanian Dinar', 'د.ا'),
  kwd('KWD', 'Kuwaiti Dinar', 'د.ك'),
  bhd('BHD', 'Bahraini Dinar', 'د.ب'),
  omr('OMR', 'Omani Rial', 'ر.ع.'),
  qar('QAR', 'Qatari Riyal', 'ر.ق'),
  lkr('LKR', 'Sri Lankan Rupee', 'Rs'),
  pkr('PKR', 'Pakistani Rupee', '₨'),
  bdt('BDT', 'Bangladeshi Taka', '৳'),
  npr('NPR', 'Nepalese Rupee', 'Rs'),
  mmk('MMK', 'Myanmar Kyat', 'K'),
  khr('KHR', 'Cambodian Riel', '៛'),
  lak('LAK', 'Lao Kip', '₭'),
  mnt('MNT', 'Mongolian Tugrik', '₮'),
  uzs('UZS', 'Uzbekistani Som', 'so\'m'),
  kzt('KZT', 'Kazakhstani Tenge', '₸'),
  azn('AZN', 'Azerbaijani Manat', '₼'),
  gel('GEL', 'Georgian Lari', '₾'),
  amd('AMD', 'Armenian Dram', '֏'),
  kes('KES', 'Kenyan Shilling', 'KSh'),
  tzs('TZS', 'Tanzanian Shilling', 'TSh'),
  ugx('UGX', 'Ugandan Shilling', 'USh'),
  ngn('NGN', 'Nigerian Naira', '₦'),
  ghs('GHS', 'Ghanaian Cedi', '₵'),
  xof('XOF', 'West African CFA Franc', 'CFA'),
  xaf('XAF', 'Central African CFA Franc', 'FCFA'),
  etb('ETB', 'Ethiopian Birr', 'Br'),
  mur('MUR', 'Mauritian Rupee', '₨'),
  dzd('DZD', 'Algerian Dinar', 'د.ج'),
  lyd('LYD', 'Libyan Dinar', 'ل.د'),
  sdg('SDG', 'Sudanese Pound', 'ج.س.'),
  aoa('AOA', 'Angolan Kwanza', 'Kz'),
  bwp('BWP', 'Botswana Pula', 'P'),
  mzn('MZN', 'Mozambican Metical', 'MT'),
  zmw('ZMW', 'Zambian Kwacha', 'ZK'),
  zwd('ZWD', 'Zimbabwean Dollar', 'Z\$'),
  afn('AFN', 'Afghan Afghani', '؋'),
  irr('IRR', 'Iranian Rial', '﷼'),
  iqd('IQD', 'Iraqi Dinar', 'ع.د'),
  syp('SYP', 'Syrian Pound', '£S'),
  lbp('LBP', 'Lebanese Pound', 'ل.ل'),
  yer('YER', 'Yemeni Rial', '﷼'),
  bob('BOB', 'Bolivian Boliviano', 'Bs.'),
  pyg('PYG', 'Paraguayan Guarani', '₲'),
  uyu('UYU', 'Uruguayan Peso', '\$U'),
  vef('VEF', 'Venezuelan Bolívar', 'Bs.F'),
  gtq('GTQ', 'Guatemalan Quetzal', 'Q'),
  hnl('HNL', 'Honduran Lempira', 'L'),
  nio('NIO', 'Nicaraguan Córdoba', 'C\$'),
  crc('CRC', 'Costa Rican Colón', '₡'),
  pab('PAB', 'Panamanian Balboa', 'B/.'),
  dop('DOP', 'Dominican Peso', 'RD\$'),
  jmd('JMD', 'Jamaican Dollar', 'J\$'),
  ttd('TTD', 'Trinidad & Tobago Dollar', 'TT\$'),
  bsd('BSD', 'Bahamian Dollar', 'B\$'),
  bbd('BBD', 'Barbadian Dollar', 'Bds\$'),
  xcd('XCD', 'East Caribbean Dollar', 'EC\$'),
  bzd('BZD', 'Belize Dollar', 'BZ\$'),
  gyd('GYD', 'Guyanese Dollar', 'G\$'),
  srd('SRD', 'Surinamese Dollar', '\$'),
  htg('HTG', 'Haitian Gourde', 'G'),
  awg('AWG', 'Aruban Florin', 'ƒ'),
  ang('ANG', 'Netherlands Antillean Guilder', 'ƒ'),
  fkp('FKP', 'Falkland Islands Pound', '£'),
  gip('GIP', 'Gibraltar Pound', '£'),
  shp('SHP', 'Saint Helena Pound', '£'),
  ssp('SSP', 'South Sudanese Pound', '£'),
  scr('SCR', 'Seychellois Rupee', '₨'),
  mvr('MVR', 'Maldivian Rufiyaa', 'Rf'),
  btn('BTN', 'Bhutanese Ngultrum', 'Nu.'),
  wst('WST', 'Samoan Tala', 'T'),
  top('TOP', 'Tongan Paʻanga', 'T\$'),
  fji('FJD', 'Fijian Dollar', 'FJ\$'),
  pgk('PGK', 'Papua New Guinean Kina', 'K'),
  vuv('VUV', 'Vanuatu Vatu', 'Vt'),
  xpf('XPF', 'CFP Franc', '₣'),
  sbd('SBD', 'Solomon Islands Dollar', 'SI\$'),
  kid('KID', 'Kiribati Dollar', '\$'),
  twd('TWD', 'New Taiwan Dollar', 'NT\$'),
  lsl('LSL', 'Lesotho Loti', 'L'),
  szl('SZL', 'Swazi Lilangeni', 'L'),
  nad('NAD', 'Namibian Dollar', 'N\$'),
  bnd('BND', 'Brunei Dollar', 'B\$'),
  kyd('KYD', 'Cayman Islands Dollar', 'CI\$'),
  bmd('BMD', 'Bermudian Dollar', '\$'),
  cve('CVE', 'Cape Verdean Escudo', '\$'),
  gmd('GMD', 'Gambian Dalasi', 'D'),
  gnf('GNF', 'Guinean Franc', 'Fr'),
  lrd('LRD', 'Liberian Dollar', 'L\$'),
  sll('SLL', 'Sierra Leonean Leone', 'Le'),
  rsd('RSD', 'Serbian Dinar', 'din'),
  mkd('MKD', 'Macedonian Denar', 'ден'),
  all('ALL', 'Albanian Lek', 'L'),
  bam('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM'),
  mdl('MDL', 'Moldovan Leu', 'L'),
  uah('UAH', 'Ukrainian Hryvnia', '₴'),
  byn('BYN', 'Belarusian Ruble', 'Br'),
  kgs('KGS', 'Kyrgyzstani Som', 'som'),
  tjs('TJS', 'Tajikistani Somoni', 'ЅМ'),
  tmr('TMT', 'Turkmenistani Manat', 'm');

  final String code;
  final String name;
  final String symbol;

  const Currency(this.code, this.name, this.symbol);

  static Currency? fromCode(String code) {
    try {
      return Currency.values.firstWhere(
        (c) => c.code.toUpperCase() == code.toUpperCase(),
      );
    } catch (e) {
      return null;
    }
  }

  static String getSymbol(String code) {
    final currency = fromCode(code);
    return currency?.symbol ?? code;
  }

  static String getName(String code) {
    final currency = fromCode(code);
    return currency?.name ?? code;
  }

  String get displayName => '$symbol $code - $name';
}
